CHANGELOG.md, Cargo.toml, src/hazmat.rs, src/hazmat/gcd.rs, src/hazmat/lucas.rs
Fixes #1 
According to Robert Baillie himself (from private correspondence), strictly speaking the `gcd(Q, n) == 1` check is necessary. Of course, in practice the Lucas test will be executed on a pre-sieved `n`, and `Q` is always small, so this condition is satisfied automatically. But in order to avoid having implicit assumptions in the code (since `lucas_test()` is public), this PR adds the GCD check. The performance impact is negligible, so why not.
=> Add a GCD check to the Lucas test

CHANGELOG.md, benches/bench.rs, src/hazmat.rs, src/hazmat/jacobi.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs, src/traits.rs
- When looking for safe primes only check numbers == 3 mod 4 (~2x speedup)
- Handle various corner cases in `Sieve`
- Add a benchmark for `safe_prime()`
- Add a bunch of tests to bump coverage
=> Better sieving

CHANGELOG.md, benches/bench.rs, src/hazmat.rs, src/hazmat/miller_rabin.rs, src/hazmat/precomputed.rs, src/hazmat/sieve.rs, src/presets.rs
Public changes:
- Precompute reciprocals for sieving (performance increase)
- Perform combined sieving (check the residues of both `n` and `n/2`) when searching for safe primes (a dramatic performance increase)
- Don't run sieving in `is_prime()` etc - BPSW is enough, and sieving only slows the test down.
- `sieve_once()` is removed.
Other changes:
- Removed `decompose()` since we now have `trailing_zeros()` available
- Organized existing benchmarks to better isolate the components
- Added GMP and OpenSSL benchmarks
=> Sieving improvements

CHANGELOG.md, benches/bench.rs, src/hazmat/miller_rabin.rs, src/presets.rs, src/traits.rs
- Use bounded exponentiation in the MR test taking the bit size of the given candidate.
- Take `Option<usize>` in random prime generation functions, to avoid repetition of the size in most cases (where it is equal to the Uint size) 
MR is the first check that's being run after the sieve, so this can noticeably increase the performance. For example, for the case of `U256`  and a 128 bit bound the speedup of `safe_prime()` is 3.5x (but still 3x slower than U128 with 128 bits).
An example use case: in CGGMP21 scheme, the selected primes `p`, `q` for the Paillier encryption must be big enough for `p * q` to cover the range of squared secp256k1 scalars. This means that `bits(p * q) > 512`. Naturally, for testing purposes one would go with the minimum size, so 257-bit primes and `U320` type. …
=> Bounded MR test

CHANGELOG.md, benches/bench.rs, src/lib.rs, src/presets.rs, src/traits.rs
Rename `prime()` to `generate_prime()`, `safe_prime()` to `generate_safe_prime()`, `prime_with_rng()` to `generate_prime_with_rng()`, `safe_prime_with_rng()` to `generate_safe_prime_with_rng()`. Functions should have verb phrase names, and it also makes it easier to search for them
=> Use verbs instead of nouns for prime-generation functions

CHANGELOG.md, README.md, src/hazmat/jacobi.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs
- Fixed some comment typos 
- Added a `max_bit_length == 0` check in `Sieve::new()` (NCC-E008526-K2E)
- Replaced `wrapping_add()` with `checked_add()` calls to detect possible contract violations early (NCC-E008526-QTR)
- Removed a check for `a == i32::MIN` in `jacobi_symbol()` (`abs_diff()` handles this case just fine)
- Using A* by default for the Lucas test
=> NCC audit fixes

CHANGELOG.md, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs
`CtOption::expect()` was introduced in `subtle` 2.5. `crypto-bigint` 0.5.2 depends on `subtle` 2.4, so this PR changes the uses of `expect` to the API available there instead.
=> Relax the `subtle` version requirement

CHANGELOG.md, Cargo.toml
- pin MSRV to 1.65 in Cargo.toml
- add lower bound `openssl=0.10.39` (compilation fails before that)
- add lower bound `rand_core=0.6.4` (`CryptoRngCore` introduced; the previous `0.6` worked before because `crypto-bigint` had 0.6.4 in the dependencies, but since we're using that trait too, we should also bound it)
=> Pin MSRV and the lower bound of some dependencies

.github/workflows/crypto-primes.yml, CHANGELOG.md, Cargo.toml, benches/bench.rs, src/hazmat/gcd.rs, src/hazmat/jacobi.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/precomputed.rs, src/hazmat/sieve.rs, src/presets.rs, src/traits.rs
- Update for the changes in the API. In particular, all `bit_length` parameters are of type `u32` now.
- Use `Odd` where appropriate.
- Bump MSRV to 1.73 to match `crypto-bigint`.
=> Bump `crypto-bigint` to 0.6.0-pre.5

CHANGELOG.md, Cargo.toml, benches/bench.rs, src/hazmat/jacobi.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs, src/traits.rs
This may supersede #39. It uses `*_like` constructors (see https://github.com/RustCrypto/crypto-bigint/pull/533) instead of automatic widening, which I think is a safer approach. 
The 1024 bit safe prime generation is about 30% slower for `BoxedUint` compared to `Uint`. Not too bad for a start, but clearly there is room for improvement.
@xuganyu96 sorry, tried to base it on your PR, but I guess I changed the first commit too much, and it's not assigned to you anymore.
=> `BoxedUint` support

Cargo.toml, src/presets.rs
Until we can use a fixed version, best pin crypto-bigint to known-good version.
=> Pin crypto-bigint to rc.2 until rc.6 is out

Cargo.toml, benches/bench.rs
- Add performance tests for realistic Sieve iterations
- Add performance tests against glass-pumpkin
`glass-pumpkin` uses more MR tests than required by BPSW, so in the performance tests I used custom method to mimic that behavior. The results (against `crypto-bigint=0.6.0-rc.2`):
1024 bits: 
- `crypto-primes` default: 29ms
- `crypto-primes`, matched with `glass-pumpkin`: 39ms
- `glass-pumpkin`: 46ms
1024 bits, safe prime: 
- `crypto-primes` default: 1.33s
- `crypto-primes`, matched with `glass-pumpkin`: 1.4s
- `glass-pumpkin`: 1.43s
=> More perf tests

src/hazmat/miller_rabin.rs, src/hazmat/primes.rs, src/presets.rs
Context: https://github.com/entropyxyz/crypto-primes/pull/48/files#r1786915843
Not sure this is any better though; at least this test is closer to where the actual problem is.
=> Test a prime with 128 zeroes

.github/workflows/crypto-primes.yml
`cargo-careful` runs tests "extra carefully" and is a middle ground between just running tests and running miri: it finds more UB than the former, and less than the latter.
=> Add cargo-careful to CI

CHANGELOG.md, Cargo.toml, benches/bench.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs, src/traits.rs
An attempt to provide a more ergonomic API that works for both heap and stack allocated uints.
Before we had:
```rust
// `…where T: Integer + RandomBits`
let n = random_odd_integer::<T>(rng, NonZeroU32::new(bit_length).unwrap(), bits_precision);
let p = generate_prime_with_rng::<U1024>(&mut rng, 1024, 1024);
```
With this PR:
```rust
let n = random_odd_integer::<T>(rng, NonZeroU32::new(bit_length).unwrap());
let p = generate_prime_with_rng::<U1024>(&mut rng, 1024);
```
I think this is a more ergonomic public API.
Perhaps more contentiously, this PR also switches to prefer passing numeric parameters by value rather than by reference. 
If reviewers think this makes the PR too noisy to review, I can split out those changes.
=> Remove bit precision from the public API

src/hazmat/gcd.rs, src/hazmat/lucas.rs
Adds binary GCD to the final step of our `gcd_vartime`.
The speedup is real but marginal. 
Before:
```
fastest       │ slowest       │ median        │ mean          │ samples │ iters    
Uint<16>   217.1 ns      │ 1.226 µs      │ 245 ns        │ 245.6 ns      │ 79978   │ 2559296
Uint<32>   327.8 ns      │ 1.004 µs      │ 346.1 ns      │ 346.8 ns      │ 99701   │ 1595216
Uint<64>   527.8 ns      │ 1.879 µs      │ 553.9 ns      │ 555.6 ns      │ 110265  │ 882120
```
After:
```
fastest       │ slowest       │ median        │ mean          │ samples │ iters
Uint<16>   184.3 ns      │ 842.4 ns      │ 192.7 ns      │ 200.2 ns      │ 93287   │ 2985184
Uint<32>   271.4 ns      │ 1.41 µs       │ 298.9 ns      │ 299.3 ns      │ 109994  │ 1759904
Uint<64>   449.7 ns      │ 5.069 µs      │ 494.2 ns …
```
=> Add binary GCD

src/hazmat/sieve.rs
Avoids a panic when initializing a `Sieve` with `T::MAX`.
=> Fix overflow when initializing a Sieve with T::MAX

src/hazmat/precomputed.rs, src/hazmat/sieve.rs
A very minor optimization. For "small" startting values it's around 5% faster.
=> Cast start to u16 rather than the SMALL_PRIMES to T

CHANGELOG.md, Cargo.toml
The last published version pins crypto-bigint to rc.2 making it impossible for e.g. synedrion to move on to rc.6, hence this proposal to relax the version requirement and publish a pre.2.
=> Prepare v0.6.0-pre.2

benches/bench.rs, src/hazmat/gcd.rs, src/hazmat/jacobi.rs, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs
Tries to address #56 to the extent possible.
TL;DR is that we must use `crypto_bigint::NonZero` for all non-primitive types.
This PR just makes it explicit which variant we're using by renaming the type to `CTNonZero` and prefers core's `NonZero` wherever possible.
Given that `ZeroablePrimitive` is not on the path to stabilization any time soon, I suggest this closes #56.
=> Prefer core::num::NonZero over crypto_bigint::NonZero where possible

CHANGELOG.md, Cargo.toml, README.md, benches/bench.rs, src/lib.rs, src/presets.rs
This adds a new function to the public API, named "par_generate_prime_with_rng", that parallelizes the search for primes.
Outstanding tasks:
During this work I have tried out several different parallel implementations, using `rayon` and `chili`. The latter is a new take on low-overhead parallelism and is attractive for its small code size and advertised performance, but in my tests I have not seen good performance from it (see below).
When searching for random primes we do not know how many iterations it will take, only that we will eventually find one. This is reflected in the benchmark results as a big variability, as seen in the "fastest" and "slowest" columns below.
Unsurprisingly, the larger the prime we're looking for, the more we benefit from parallelizing the work. For `Uint<64>`s …
=> Parallel prime generation

CHANGELOG.md, benches/bench.rs, src/hazmat.rs, src/hazmat/miller_rabin.rs, src/hazmat/sieve.rs, src/presets.rs
In the RSA application one needs two primes which, when multiplied, produce a number with a fixed bit length. This can be achieved by requiring two most significant bits to be set on each. The current code just sets the MSB by default, and setting the second one requires writing a custom wrapper over `SmallPrimesSieveFactory`.
This PR attempts to provide a simpler pathway for most common bit-setting cases: no bits set (primes generated up to the chosen bit length), MSB set, and two MSBs set. `random_odd_uint()` and `SmallPrimesSieveFactory` constructors get an additional `SetBits` parameter.
An RSA application would have to use the new functionality by calling 
```rust
sieve_and_find(
rng,
SmallPrimesSieveFactory::new(bit_length, SetBits::TwoMsb),
is_prime_with_rng,
)
```
The default …
=> Allow custom MSB setting in generated primes

CHANGELOG.md, benches/bench.rs, benches/cctv.rs, src/hazmat/lucas.rs, src/lib.rs, src/presets.rs, src/traits.rs
Fixes #21
- Add `LucasCheck::Bpsw21` implementing the checks described in Baillie et al
- Use it as the default primality check
- Remove `is_prime_with_rng()` and `is_safe_prime_with_rng()`, since the new check is deterministic.
=> Implement the improved Lucas test from Baillie et al '21

.github/workflows/ci.yml, CHANGELOG.md, Cargo.toml, src/hazmat/sieve.rs
Fixes #25, and checks for 32/64 bit platform dependencies
Also bumping crypto-bigint to 0.7.0-pre.1, and MSRV to 1.85 to match crypto-bigint.
=> Add vector tests

.github/workflows/ci.yml, src/hazmat/lucas.rs, src/hazmat/miller_rabin.rs, src/hazmat/primecount.rs
- Run a benchmark test (`cargo test --benches` runs the benchmarks once to make sure the code inside is actually operational)
- Add a doc building step
- Add a semver check step
Also the doc building step uncovered some errors in the doc syntax, which in turn uncovered that `rustdoc` changed the footnote processing logic at some point between crypto-primes 0.4 and 0.5. Namely, in order to be rendered properly, footnotes cannot start with a line break. That is, this won't render correctly:
```
/// [^Baillie1980]:
///   R. Baillie, S. S. Wagstaff, "Lucas pseudoprimes",
```
but this will:
```
/// [^Baillie1980]: R. Baillie, S. S. Wagstaff, "Lucas pseudoprimes",
```
=> CI improvements

.cargo/config.toml, Cargo.toml, resources/docs-header.html, src/hazmat/primecount.rs
Add the Katex js library to the rustdocs-generated HTML header so it loads and renders any LaTeX code in the docs.
Here's what it looks like in my browser:
=> Add LaTeX rendering and translate estimate_primecount docs to LaTeX.
